
services:
  web:
    build: ./
    command: gunicorn sub_search.wsgi:application --bind 0.0.0.0:8000 --log-level debug
    volumes:
      - ./:/usr/src/app/
      - media_volume:/usr/src/app/media/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  redis:
    image: redis:7-alpine

  celery:
    build: .
    command: celery -A sub_search worker -l INFO --concurrency=4
    volumes:
        - .:/usr/src/app
        - media_volume:/usr/src/app/media/
    environment:
        - DEBUG=1
        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
        - CELERY_BROKER=redis://redis:6379/
        - CELERY_BACKEND=redis://redis:6379/
    depends_on:
        - web
        - redis
        - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  
  nginx:
    build: ./nginx
    volumes:
      - media_volume:/usr/src/app/media/
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data:
  media_volume: